# 使用 Go 1.21 作為基礎映像
FROM golang:1.23-alpine

# 設定工作目錄
WORKDIR /app

# 複製 go.mod 和 go.sum 文件（如果存在）
COPY go.mod ./
COPY go.sum ./

# 下載依賴
RUN go mod download

# 複製源代碼
COPY . .

# 編譯應用
RUN go build -o main .

# 執行應用
CMD ["./main"]